useFixtures: false

elasticsearch:
 host: 'https://search-talktofrank-elastic-alpha-rqcui3cnc7qs3i2ns5glqw4m7i.eu-west-2.es.amazonaws.com/'
 drugResultCount: 3
 suggestResultCount: 5
 phraseResultCount: 3
 showESResult: false

sentry:
 dsn: 'https://ba8d45f8851c4c84b311a037444e3d23@sentry.io/1286883'