buildConfig: production
api: https://alpha-talktofrank.cxp.io

contentful:
  contentHost: 'https://preview.contentful.com'
  contentSpace: 'mltlrs3kods6'
  contentAccessToken: !!import/single '../config.creds.yaml'
  contentTypes:
    drug: 'drugPage'

sentry:
 dsn: !!import/single '../config.sentry.yaml'
 logErrors: false

basicAuth:
  username: 'admin'
  password: 'password'